### ISSUE TITLE
more than one actions checked

### ISSUE THREAD

**Issue by szweee** [mezhevikin/AlertController#2]
I want to check more than one actions, but each time one is checked, alertController will dismiss. How can I prevent it from dismiss after checked?

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by mezhevikin** [comment]
Hi. Unfortunately you can't do it, because UIAlertController dismiss
controller after performing any action.  My lib is small wrapper around
UIAlertController.

**Comment by szweee** [comment]
Isn't there a way to stop the alertcontroller from dismiss when selected?
